name: React Build
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: checkout source code
        uses: actions/checkout@master

      - name: Install Dependencies
        run: npm install && npm install -g serve

      - name: Build
        run: npm run build

      - name: Start
        run: serve -s build
